### ISSUE TITLE
Going long issue

### ISSUE THREAD

**Issue by achafetz** [noahbartlett/Me_One_Last_Kiss#12]
@noahbartlett, just FYI I'm running into issues with the below code.

https://github.com/noahbartlett/Me_One_Last_Kiss/blob/c4ae720a280a786022d5b03de1f6a2465632f302/R%20Files/02_FY18Q2Tableau.R#L94-L114

The code worked well when testing on one country's dataset, but R stalls out trying to make the dataset long when its already at 5.7 million rows when wide.

Will adjust so it's done in pieces similar to the original, but via a function and submit another pull request.

**Comment by noahbartlett** [comment]
It crashed my computer.

You might want to go back to the original code for that section since it
worked just fine. Unless there's a specific reason for changing it that I'm
not aware of.

**Comment by achafetz** [comment]
Fixed with the pull request
